FROM node:20

RUN apt-get update && apt-get install -y \
    chromium \
    iproute2 \
    net-tools \
    iputils-ping \
    tcpdump \
    procps \
    python3 \
    python3-pip \
    python3-venv \
    tesseract-ocr \
    tesseract-ocr-eng \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages pytesseract pillow

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

CMD ["npm", "test"]