FROM node:20-alpine

RUN apk add --no-cache \
    build-base \
    python3 \
    py3-pip \
    make \
    g++

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3002
EXPOSE 10000-10100/udp

CMD ["npm", "start"]
